-- Migration: Tambah kolom GL Values ke tr_ros_header
-- Tanggal: 10-07-2026
-- Fitur: Simpan nilai COA saat save ROS

ALTER TABLE tr_ros_header
  ADD COLUMN gl_persediaan_intransit DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1105-01-03 - PERSEDIAAN BAHAN BAKU INTRANSIT',
  ADD COLUMN gl_advance_purchase DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1104-01-02 - ADVANCE PURCHASE',
  ADD COLUMN gl_unbill DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 2101-01-06 - HUTANG BELUM TERTAGIH',
  ADD COLUMN gl_bm_dibayar_dimuka DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1108-01-09 - BM DIBAYAR DIMUKA',
  ADD COLUMN gl_prepaid_ls DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1111-01-01 - PREPAID EXPENSE LS',
  ADD COLUMN gl_hutang_forwarding DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 2104-01-14 - HUTANG BIAYA FORWADING',
  ADD COLUMN gl_prepaid_insurance DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1111-01-02 - PREPAID EXPENSE INSURANCE',
  ADD COLUMN gl_prepaid_other DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 1111-01-03 - PREPAID EXPENSE OTHER',
  ADD COLUMN gl_selisih_kurs DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 7201-01-07 - B. SELISIH KURS (positif=debet, negatif=kredit)',
  ADD COLUMN gl_pembulatan DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'COA 7201-01-05 - B. PEMBULATAN (positif=debet, negatif=kredit)',
  ADD COLUMN gl_unbill_kurs DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'Nilai unbill dalam kurs',
  ADD COLUMN gl_advance_purchase_kurs DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'Nilai advance purchase dalam kurs';
